### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ShuaiXuan** [wencolani/IterE#11]
I run it but
Process Process-3:
Process Process-2:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
if dat == None:
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
if dat == None:
File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
if dat == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by ShuaiXuan** [comment]
I run it  but
Process Process-3:
Process Process-2:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
    if dat == None:
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
    if dat == None:
  File "/Users/apple/.conda/envs/IterE-master/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/Downloads/IterE-master/data.py", line 892, in negative_triple_generator
    if dat == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by loxs123** [comment]
if dat == None:改为if dat is None:
