### ISSUE TITLE
Error when running your code on FB15k-237-sparse

### ISSUE THREAD

**Issue by bagindokemas** [wencolani/IterE#3]
Dear Authors,

I found these errors when running IterE (the main.py file) on FB15k-237-sparse dataset.

Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 66, in main
    inject_triple_percent = option.inject_triple_percent)
  File "/uoa/scratch/users/r01krw16/IterE/data.py", line 58, in __init__
    self.train_ids = self._triple2id(self.train_triples)
  File "/uoa/scratch/users/r01krw16/IterE/data.py", line 143, in _triple2id
    for (h,r,t) in triples]
  File "/uoa/scratch/users/r01krw16/IterE/data.py", line 143, in <listcomp>
    for (h,r,t) in triples]
KeyError: '/m/06cx9'

Can you advise me how to solve this problem? Thank you.

**Comment by wencolani** [comment]
The data for FB15k-237-sparse it form in 'h \t r \t h' per line, while the code is for data 'h \t t \t r' per line. So please replace line 108 with line 109 in data.py, then it should work for FB15k-237-sparse dataset.
